### ISSUE TITLE
added to an awesome list

### ISSUE THREAD

**Issue by EMLVIRUS** [fcFn/traymond#1]
Hey, I'm maintianing https://github.com/EMLVIRUS/Amazing-Windows-Apps
I have created the [issue](https://github.com/EMLVIRUS/Amazing-Windows-Apps/issues/90) for you.
If you don't mind I'm listing you project into [system](https://github.com/EMLVIRUS/Amazing-Windows-Apps/blob/master/system.md) category.
Any other request, just let me know.

**Comment by fcFn** [comment]
Ah! Fame and glory awaits!
