### ISSUE TITLE
Traymond shows a crashing window and Traymond processes remain after kill them

### ISSUE THREAD

**Issue by tomasorti** [fcFn/traymond#10]
I will provide a animated gif of Traymond crashing in next Windows reboot.
Meanwhile here are some screenshots of two process tools not being able to finish/kill Traymond.

ProcessHacker:
![traymond-prochacker](https://user-images.githubusercontent.com/2485147/62040992-f0b75d80-b1fa-11e9-9d3d-a28472048545.gif)

Process Explorer:
![traymond-processExplorer](https://user-images.githubusercontent.com/2485147/62041008-f9a82f00-b1fa-11e9-8ff8-7a3afb6ec37c.gif)

Unfortunately, TaskManager does not show Traymond process when executed as **Run as administrator** and if executed as user, it does not allow to kill/finish it.
![traymond-taskManager](https://user-images.githubusercontent.com/2485147/62041358-c1edb700-b1fb-11e9-853d-cf253a99da78.gif)

Funny that my user has **Administrator** permissions... Oh God, Windows!
By the way, this was tested on Windows 10: `OS Version:                10.0.16299 N/A Build 16299`

**Comment by fcFn** [comment]
Oh, wow, thanks for the pictures.

Could you please tell how does this lingering process appear? Does Traymond crash beforehand and then it leaves its unkillable process around? If so, how does the crash happen? If not, please tell me the steps to reproduce this.

**Comment by tomasorti** [comment]
Ok, I think I know why is crashing...
Compiled it for architecture `x86` (starting CMD with `vcvarsall.bat x86`) and it works.
It is just a matter of fixing it to work with `x64`.

Below an animated gif with `git diff`, `git branch`, `git remote`, compilation, run & crash:

![traymond-compile-run](https://user-images.githubusercontent.com/2485147/62151553-d9629800-b300-11e9-8655-2ee374e5a813.gif)

Will keep an eye on your fix!
😉

**Comment by fcFn** [comment]
If you could explain why you need it compiled to x64, please reopen the issue.
