### ISSUE TITLE
doesn't run with hotkey occupied

### ISSUE THREAD

**Issue by EMLVIRUS** [fcFn/traymond#2]
When the hotkey is occupied (I guess most probably win+Z), the app doesn't run. It doesn't help with Administrator
IMHO, the app should run anyway with option to change the hotkey

![image](https://cloud.githubusercontent.com/assets/16912240/25788375/29cc6fd4-33db-11e7-9842-2d53bae455c7.png)

**Comment by ivysrono** [comment]
+1

**Comment by fcFn** [comment]
You will have to change that in code as per [readme](https://github.com/fcFn/traymond#customizing) and recompile.

Feel free to create a PR to add the option to change the hotkey during run time.

**Comment by EMLVIRUS** [comment]
@fcFn Maybe I missed something:
My Win+Z hotkey is always empty. In that case, Traymond is supposed to register it sucessfully.
Am I misunderstanding anything?

**Comment by fcFn** [comment]
That was a misunderstanding on my part then. I thought you said it's occupied (in that case you either clear it up for use by the app or change the key in the source code and rebuild). I don't have much time for this project anymore, but If I do get time, I'll maybe whip up some logging, because this isn't supposed to happen (tested on a few machines) and I can't reproduce it.

**Comment by EMLVIRUS** [comment]
Maybe OS compatibility issue? This is what I'm using
![image](https://cloud.githubusercontent.com/assets/16912240/25854271/05336a06-3502-11e7-93e8-69534a1eb35e.png)
(Windows 10 Home)

**Comment by ivysrono** [comment]
Win10 Pro x64 1703
reproduce.

**Comment by fcFn** [comment]
Thanks for the info. I'll try to reproduce on a Win 10 machine.

**Comment by EMLVIRUS** [comment]
@fcFn Glad to see that fix. I have [add your app into my list](https://github.com/AmazingApps/Amazing-Windows-Apps/commit/b1fec2f2a95dc25f3084804503dd61aa0a3ce96d) just now.
Grateful for your great work again.
If any other request, just let me know
