### ISSUE TITLE
Does not work with some system apps

### ISSUE THREAD

**Issue by EMLVIRUS** [fcFn/traymond#3]
Basically all UWP apps, Traymond doesn't work with them even with admin privilege.

Correct: it does work with Task Manager, sorry

**Comment by fcFn** [comment]
Thanks! I'm looking into it.

**Comment by fcFn** [comment]
Unfortunately I cannot fix that as UWP apps are run in sandbox and couldn't be accessed from outside (Administrator mode won't help either).
