### ISSUE TITLE
Icons lost when explorer is restarted

### ISSUE THREAD

**Issue by Rictusempra** [fcFn/traymond#4]
STR:
1. run Traymond and minimize any window
1. restart explorer.exe from Task Manager or somewhere else

Actual Results:
All minimized icons are gone together with Traymond itself

**Comment by fcFn** [comment]
Thanks for reporting this! I'll look into it.

**Comment by fcFn** [comment]
Most windows can be restored after explorer crash by killing Traymond in task manager and starting it again. It will put the icons back into tray area from where you can restore them.
