### ISSUE TITLE
Can't minimize again when open the windows in other way

### ISSUE THREAD

**Issue by linsui** [fcFn/traymond#8]
When I use Thunderbird, I can click on the notification to open the window, but the icon in tray won't disapper. So I have to double click on the icon to make it disappear or I can't minimize the windows into tray again.
Thanks for this great software anyway.

**Comment by fcFn** [comment]
Thanks for reporting the issue, @linsui. I'll try to carve out some time to look into it, but unfortunately I cannot promise anything.

Glad you're enjoying my little app! 🤗

**Comment by fcFn** [comment]
Hey, I just shipped a new release and I believe your issue should be fixed. 

If the issue still persists, please reopen the issue and post your Windows version.

**Comment by linsui** [comment]
It works like a champ! Thanks!
