### ISSUE TITLE
The taskbar icon disappears when the desktop is restarted

### ISSUE THREAD

**Issue by xuejianbest** [fcFn/traymond#9]
When traymond started and  minimized some windows. When the windows desktop restarted, then the traymond and minimized windows taskbar icon is disappeared.

**Comment by fcFn** [comment]
Hello!

Hey, have you tried killing it via Task Manager and restarting? The app keeps track of the windows it manages in a file in the root of the directory where the executable is located. When launching Traymond, it tries to read this file and restore all the windows.

**Comment by xuejianbest** [comment]
Yes. Even if this is a bit cumbersome, kill and restart it's works !  Thinks!

**Comment by fcFn** [comment]
Glad it worked. As for cumbersomeness, it's only required in a rare case of either app crash/kill or Explorer restart, so I employed YAGNI.
